// components/list/leftSideTab/leftSideTab.js
Component({
  /**
   * 组件的属性列表
   */
  properties: {
      classList:Array
  },

  /**
   * 组件的初始数据
   */
  data: {
      tapIndex:0,
      /*classList:[
          {
              id:1,
              className:'热门推荐',
              adImg:'',
              class2List:[
                  {
                      id:11,
                      className:'吃货必选',
                      class3List:[
                          {
                              id:111,
                              className:'冲调饮品',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'零食礼包',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'每日坚果',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'进口水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'咖啡冲调',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
                  {
                      id:11,
                      className:'个人护理',
                      class3List:[
                          {
                              id:111,
                              className:'洗发水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'护手霜',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'面膜',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
              ]

          },
          {
              id:2,
              className:'生鲜水果',
              adImg:'',
              class2List:[
                  {
                      id:11,
                      className:'吃货必选2',
                      class3List:[
                          {
                              id:111,
                              className:'冲调饮品',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'零食礼包',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'每日坚果',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'进口水',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
                  {
                      id:11,
                      className:'个人护理2',
                      class3List:[
                          {
                              id:111,
                              className:'洗发水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'护手霜',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'面膜',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
              ]

          },
          {
              id:3,
              className:'休闲零食',
              adImg:'',
              class2List:[
                  {
                      id:11,
                      className:'吃货必选',
                      class3List:[
                          {
                              id:111,
                              className:'冲调饮品',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'零食礼包',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'每日坚果',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'进口水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'咖啡冲调',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
                  {
                      id:11,
                      className:'个人护理',
                      class3List:[
                          {
                              id:111,
                              className:'洗发水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'护手霜',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
              ]

          },
          {
              id:4,
              className:'酒水乳饮',
              adImg:'',
              class2List:[
                  {
                      id:11,
                      className:'吃货必选',
                      class3List:[
                          {
                              id:111,
                              className:'冲调饮品',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'零食礼包',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'每日坚果',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'进口水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'咖啡冲调',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
                  {
                      id:11,
                      className:'个人护理',
                      class3List:[
                          {
                              id:111,
                              className:'洗发水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'护手霜',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'面膜',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
              ]

          },
          {
              id:5,
              className:'粮油副食',
              adImg:'',
              class2List:[
                  {
                      id:11,
                      className:'吃货必选',
                      class3List:[
                          {
                              id:111,
                              className:'冲调饮品',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'零食礼包',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'每日坚果',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'进口水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'咖啡冲调',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
                  {
                      id:11,
                      className:'个人护理',
                      class3List:[
                          {
                              id:111,
                              className:'洗发水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'护手霜',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'面膜',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
              ]

          },
          {
              id:6,
              className:'个人护理',
              adImg:'',
              class2List:[
                  {
                      id:11,
                      className:'吃货必选',
                      class3List:[
                          {
                              id:111,
                              className:'冲调饮品',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'零食礼包',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'每日坚果',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'进口水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'咖啡冲调',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
                  {
                      id:11,
                      className:'个人护理',
                      class3List:[
                          {
                              id:111,
                              className:'洗发水',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'护手霜',
                              class3Img:'/res/small1.png',
                          },
                          {
                              id:111,
                              className:'面膜',
                              class3Img:'/res/small1.png',
                          },
                      ]
                  },
              ]

          },
      ],*/
      /*class1:[],*/
  },
  /**
   * 组件的方法列表
   */
  methods: {
      tapNav:function (e) {
          var that = this;
          var i = e.currentTarget.dataset.navindex;
          console.log('组件获取到点击标签id为'+e.currentTarget.dataset.oneid);
          that.setData({
              tapIndex:i
          });
          this.triggerEvent('tapTab', { tapIndex: i });
      },
  },
      /*ready: function () {
          let that = this;
            that.setData({
                class1:that.properties.classList
            })
      }*/
})
